const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("storybound", {
  listTasks: () => ipcRenderer.invoke("tasks:list"),
  createTask: (input) => ipcRenderer.invoke("tasks:create", input),
  deleteTask: (id) => ipcRenderer.invoke("tasks:delete", id),
  cancelTask: (id) => ipcRenderer.invoke("tasks:cancel", id),
  duplicateTask: (id) => ipcRenderer.invoke("tasks:duplicate", id),
  runQueue: (ids) => ipcRenderer.invoke("queue:run", ids),
  runTask: (id) => ipcRenderer.invoke("tasks:run", id),
  prepareTask: (id) => ipcRenderer.invoke("tasks:prepare", id),
  continueTask: (id) => ipcRenderer.invoke("tasks:continue", id),
  updatePipeline: (id, pipeline) => ipcRenderer.invoke("tasks:updatePipeline", id, pipeline),
  regenerateScene: (id, sceneIndex, kind) => ipcRenderer.invoke("tasks:regenerateScene", id, sceneIndex, kind),
  replaceSceneImage: (id, sceneIndex) => ipcRenderer.invoke("tasks:replaceSceneImage", id, sceneIndex),
  renderTask: (id) => ipcRenderer.invoke("tasks:render", id),
  getConfig: () => ipcRenderer.invoke("config:get"),
  saveConfig: (config) => ipcRenderer.invoke("config:save", config),
  testConfig: (kind, config) => ipcRenderer.invoke("config:test", kind, config),
  runDiagnostics: () => ipcRenderer.invoke("diagnostics:run"),
  getTemplates: () => ipcRenderer.invoke("templates:list"),
  saveDraftTemplate: (input) => ipcRenderer.invoke("templates:save", input),
  deleteDraftTemplate: (id) => ipcRenderer.invoke("templates:delete", id),
  listCoverTemplates: () => ipcRenderer.invoke("covers:list"),
  listBgm: () => ipcRenderer.invoke("bgm:list"),
  addBgm: () => ipcRenderer.invoke("bgm:add"),
  listLlmProfiles: () => ipcRenderer.invoke("profiles:list"),
  saveLlmProfile: (input) => ipcRenderer.invoke("profiles:save", input),
  activateLlmProfile: (id) => ipcRenderer.invoke("profiles:activate", id),
  deleteLlmProfile: (id) => ipcRenderer.invoke("profiles:delete", id),
  listVoicePresets: () => ipcRenderer.invoke("voices:list"),
  saveVoicePreset: (input) => ipcRenderer.invoke("voices:save", input),
  openPath: (target) => ipcRenderer.invoke("path:open", target),
  showInFolder: (target) => ipcRenderer.invoke("path:show", target),
  pathToDataUrl: (target) => ipcRenderer.invoke("path:dataUrl", target),
  writeClipboard: (text) => ipcRenderer.invoke("clipboard:write", text),
  generateImage: (input) => ipcRenderer.invoke("image:generate", input),
  listPlaygroundJobs: () => ipcRenderer.invoke("playground:list"),
  listStyles: () => ipcRenderer.invoke("styles:list"),
  saveStyle: (input) => ipcRenderer.invoke("styles:save", input),
  deleteStyle: (id) => ipcRenderer.invoke("styles:delete", id),
  listPromptTemplates: () => ipcRenderer.invoke("prompts:list"),
  savePromptTemplate: (input) => ipcRenderer.invoke("prompts:save", input),
  deletePromptTemplate: (id) => ipcRenderer.invoke("prompts:delete", id),
  importPromptTemplates: () => ipcRenderer.invoke("prompts:importJson"),
  selectAudio: () => ipcRenderer.invoke("files:selectAudio"),
  selectImages: () => ipcRenderer.invoke("files:selectImages"),
  selectImage: () => ipcRenderer.invoke("files:selectImage"),
  selectDirectory: (title) => ipcRenderer.invoke("files:selectDirectory", title),
  clearHistory: () => ipcRenderer.invoke("history:clear"),
  researchSource: (query, requirements, options) => ipcRenderer.invoke("source:research", query, requirements, options),
  synthesizeVoice: (input) => ipcRenderer.invoke("voice:synthesize", input),
  generateMusicMv: (input) => ipcRenderer.invoke("music:generate", input),
  onTaskEvent: (callback) => {
    const handler = (_event, payload) => callback(payload);
    ipcRenderer.on("task:event", handler);
    return () => ipcRenderer.removeListener("task:event", handler);
  }
});
